airflow:
  executor: KubernetesExecutor
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin
flower:
  enabled: false
redis:
  enabled: false
workers:
  enabled: false
dags:
  path: /airflow/dags
  gitSync:
    enabled: true
    repo: "https://github.com/angst-storm/sota-ai-experiments.git"
    branch: "main"
    revision: "HEAD"