airflow:
  executor: KubernetesExecutor
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin
  image:
    repository: customairflow
    tag: 6
flower:
  enabled: false
redis:
  enabled: false
workers:
  enabled: false
dags:
  path: /opt/airflow/dags
  persistence:
    enabled: false
  gitSync:
    enabled: false