airflow:
  executor: KubernetesExecutor
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin
flower:
  enabled: false
redis:
  enabled: false
workers:
  enabled: false