apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp4dev
  labels:
    app: smtp4dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp4dev
  template:
    metadata:
      labels:
        app: smtp4dev
    spec:
      containers:
        - name: smtp4dev
          image: rnwood/smtp4dev:3.6.1
          env:
            - name: ServerOptions__Port
              value: "2525"
          ports:
            - containerPort: 80
              name: web
            - containerPort: 2525
              name: smtp
